project:
  type: website

website:
  title: "TKF Blog"
  navbar:
    title: "Home"
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/philippeperet/
        target: _blank
      - icon: github
        href: https://github.com/thekangaroofactory
        target: _blank
      - icon: youtube
        href: https://www.youtube.com/@TheKangarooFactory
        target: _blank
format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: 
      - gfont/css/quicksand.css
      - custom.css
    include-in-header:
      text: <script type="text/javascript" src="/js/iframe-resizer.child.js"></script>
    link-external-newwindow: true
