project:
  type: website

website:
  title: "Blog"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/philippeperet/
      - icon: github
        href: https://github.com/thekangaroofactory
      - icon: youtube
        href: https://www.youtube.com/@TheKangarooFactory
format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: gfont/css/quicksand.css
