project:
  type: website

website:
  title: "TheKangarooFactory Blog"
  site-url: https://thekangaroofactory.github.io/the-kangaroo-factory-blog/
  description: "Yet another blog about data science."
  navbar:
    title: "Home"
    right:
      - icon: rss
        href: index.xml

author:
  - name: Philippe PERET
    orcid: 0009-0003-9666-7490
    url: https://www.linkedin.com/in/philippeperet/
    email: philippe.peret@hotmail.com

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: 
      - gfont/css/quicksand.css
      - custom.css
    include-in-header:
      text: <script type="text/javascript" src="/js/iframe-resizer.child.js"></script>
    link-external-newwindow: true
