project:
  type: website

website:
  title: "Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/thekangaroofactory
      - icon: linkedin
        href: https://www.linkedin.com/in/philippeperet/
format:
  html:
    theme: cosmo
    css: custom.scss

editor: visual
